### ISSUE TITLE
`pds4-tools` on conda

### ISSUE THREAD

**Issue by cmillion** [Small-Bodies-Node/pds4_tools#61]
We are attempting to make the [Planetary Data Reader (`pdr`)](https://github.com/millionconcepts/pdr) available via conda. `pds4-tools` is one of our dependencies, and it is not on conda, so we can't put our code on conda without vendoring your code, which is not our preference. Would you consider putting this package onto conda?

**Comment by LevN0** [comment]
I believe conda allows specifying pip dependencies. Does this not work?

**Comment by m-stclair** [comment]
This issue is about the conda-forge repository, not the `conda` tool. Yes, you can include instructions to install pip dependencies in an environment file. But repositories don't like this, because the `conda` solver can't ensure application binary interface compatibility with pip-installed packages, so it makes it much harder for them to maintain the integrity of their repository. For the specific conda-forge policy, see: https://conda-forge.org/docs/maintainer/adding_pkgs.html#avoid-external-dependencies

**Comment by LevN0** [comment]
Let me look into what the process for automating submissions to conda-forge is.

**Comment by LevN0** [comment]
This is in-progress, just FYI. Awaiting re-review by the conda-forge team.

**Comment by LevN0** [comment]
`pds4_tools` is [now available on conda-forge](https://anaconda.org/conda-forge/pds4_tools).

Feedstock located [here](https://github.com/conda-forge/pds4_tools-feedstock/).

**Comment by cmillion** [comment]
Great! Thank you.
