### ISSUE TITLE
PDS4 Standards Change for Line Delimiters

### ISSUE THREAD

**Issue by acraugh** [Small-Bodies-Node/pds4_tools#7]
PDS4 is planning a standards change that will allow Table-type objects to use record delimiters other than "Carriage-Return Line-Feed" - specifically, just the linefeed character.  It looks like the current delimiter requirement is hard-coded into the PDS4 viewer.  This needs to be upgraded to check the delimiter attribute in the label and act accordingly.

Contact @acraugh for PDS4 standards details as they are finalized.

**Comment by mkelley** [comment]
@acraugh Thanks!  Is there an estimated timescale for this change?

**Comment by acraugh** [comment]
The standard change?  That would be the next build, which is happening in 
March. The final decision about the new value to check for should be made 
probably in a couple weeks.  I can elevate the priority once I know we've 
got someone who can actually make the change.  I don't think I have Lev's 
current email, oddly enough...

-A.

**Comment by LevN0** [comment]
That seems like a strange choice standards wise. What is the driving force behind it?

It has been a while, but I think that Table_Character and Table_Binary should not care about record delimiter, since they are read through record_length, field_length, field_location, group_length and group_location. I am assuming that record_length will continue including the record delimiter. 

Table_Delimited would definitely need a change though. Would need to know how the information model is changing to implement anything.

**Comment by eshaya** [comment]
I tool a look at the xml read_pds code and it looks like the record 
delimiter is never explicitly used in table rows because the IDL readf 
and readu procedures take care of the two cases transparently.  The 
change may cause an indirect error if it requires record_length to be 
interpreted differently.  But, I do not think it will.

Ed

**Comment by acraugh** [comment]
On Thu, 23 Jan 2020, Lev Nagdimunov wrote:

> That seems like a strange choice standards wise. What is the driving 
> force behind it?

Sadly, I cannot seem to answer this question without becoming excessively 
sardonic.

> It has been a while, but I think that Table_Character and Table_Binary 
> should not care about record delimiter, since they are read through 
> record_length, field_length, field_location, group_length and 
> group_location. I am assuming that record_length will continue including 
> the record delimiter.

We had Pat Lawton check it out, and yes the fixed-width routines do what 
you would expect.  The delimiter will still count in record length.

> Table_Delimited would definitely need a change though. Would need to 
> know how the information model is changing to implement anything.

And that's where Pat found the problem.  Looks like the delimiter is 
hard-coded.  I expect that the <record_delimiter> attribute will acquire 
at least one and possibly two new values: "Carriage-Return" and 
"Line-Feed".  Of course it would be just like PDS to complicate it and 
come up with different bad spellings.

I'll let you know when a format decision is made.  The build would be 
coming up in March, so there's some time yet before all the CCB actions 
have to be completed.

EN also asked for a heads-up on the library.  Should I tell them you'll 
handle it?

Thanks again!

-Anne.

**Comment by acraugh** [comment]
Hey Ed - thanks for responding!

On Thu, 23 Jan 2020, Edward Shaya wrote:

> I tool a look at the xml read_pds code and it looks like the record
> delimiter is never explicitly used in table rows because the IDL readf
> and readu procedures take care of the two cases transparently.  The
> change may cause an indirect error if it requires record_length to be
> interpreted differently.  But, I do not think it will.

I would expect that to be true for fixed-width tables, but not for 
delimited tables, which by definition require the code to seek out the
record delimiter.  But perhaps the IDL code doesn't handle delimited 
tables?

-Anne.

**Comment by eshaya** [comment]
Anne,

The code handles delimited tables by using the standard IDL readf 
procedure to read each row.  That procedure seeks out either of the two 
standard terminator types.  So, read_pds.pro code was ready for this 
change from the start.

Ed

**Comment by acraugh** [comment]
Clever little environment.  OK, thanks!

-A.

**Comment by LevN0** [comment]
I will take a look. The library change should be straightforward. EN is always welcome to submit a PR, if they would like to see it sooner. Hesitant to merge into master until more details of how the standard is changing for this are finalized. 

I had intentionally hard-coded the value since the Viewer is, or was especially earlier, used as a poor man's validator and delimiters were a common error. Had not expected the value to ever change either.

**Comment by LevN0** [comment]
Has the dust settled on what this standards change will look like -- both IM and SR wise?

**Comment by jordanpadams** [comment]
@LevN0 the change has not been officially approved yet by the CCB. part of the hold up is an analysis by EN to understand how much effort and impact this change would have.

for pds4_tools, how much effort do you think it would take to complete such a change? would you say ~2-3 work hours for development, test, and release? more or less?

**Comment by LevN0** [comment]
Assuming the change is purely to add a linefeed record delimiter, a few hours to develop and add tests. Releasing is its own step.

(From a standards perspective though, I never expected the record delimiter to change because it would seem to introduce unnecessary complexity to reading data in the future. It should be easy enough for a data provider to adjust data to use CRLF. Even PDS3 did not allow this.)

**Comment by jordanpadams** [comment]
@LevN0 thanks! adding linefeed record delimiter is the only change at this time.

yeah, from a standards perspective, there are definitely good points to both sides of the argument. the DDWG seem to determine it was value-added to not require that extra processing step for data providers

**Comment by jordanpadams** [comment]
@LevN0 FYI this change has been approved for PDS4 v1.16.0.0, with expected release in late Spring.

Here is the approved SCR: 
[CCB-264.pdf](https://github.com/Small-Bodies-Node/pds4_tools/files/5884235/CCB-264.pdf)

And some test data: 
[minimal_test_product_line_endings.zip](https://github.com/Small-Bodies-Node/pds4_tools/files/5884238/minimal_test_product_line_endings.zip)

**Comment by LevN0** [comment]
@jordanpadams Thank you for the notice.

**Comment by jordanpadams** [comment]
@LevN0 as noted above, we have forked the repo and added this to our plan in the event you are unable to get to it.

**Comment by LevN0** [comment]
Should be able to get to it prior to late Spring.

**Comment by LevN0** [comment]
Not sure that test data is correct - both examples seem to use CRLF in the label? Also, the delimited tables are most likely to be affected by this, since fixed width tables (e.g. Table_Character) are more likely to be read using the given record lengths.

**Comment by jordanpadams** [comment]
@LevN0 you are right. apologies. those were the examples given by the DDWG. we are coming up with a better set for validate as we speak. i will upload here once we have some better ones.

**Comment by jordanpadams** [comment]
[github292.tar.gz](https://github.com/Small-Bodies-Node/pds4_tools/files/6053151/github292.tar.gz)

@LevN0 here is an initial set of test data. awaiting some further instruction on whether or not `Inventory` should be included
