### ISSUE TITLE
Investigate default value of  ``Label.to_dict(..., skip_attributes=bool)``

### ISSUE THREAD

**Issue by LevN0** [Small-Bodies-Node/pds4_tools#86]
The Label class provides a method to convert the label from Label (which is effectively a subclass of ElementTree) to a dictionary, namely ``Label.to_dict(...)``.

The method includes a number of optional arguments. 

One of the optional arguments is ``skip_attributes``. The effect of this argument is as follows:

Original XML,

```xml
<Table_Character>
    <offset unit="byte">0</offset>
    <records>76</records>
    ...
</Table_Character>
```

Converted to dict via ``Label.to_dict(skip_attributes=True)``,

```python
{
    "Table_Character": {
        "offset": "0",
        "records": "76"
    }
}
```

Converted to dict via ``Label.to_dict(skip_attributes=False)``,

```python
{
    "Table_Character": {
        "offset": {
            "@unit": "byte",
            "_text": "0"
        },
       "records": "76"
    }
}
```

The help string for this argument states "If True, skips adding attributes from XML. Defaults to False." However, despite this text, the argument is actually set to True by default, i.e. attributes are skipped when converting to dict.

Need to investigate whether the argument should be changed to False by default as the help string says, or whether the help string should be adjusted.

**Comment by LevN0** [comment]
@cmillion @m-stclair

I discovered this issue while looking at [this text](https://github.com/MillionConcepts/pdr/blob/925625453f14f4fbbb2c8498a4f6a8cc1f66247d/pdr/pdr.py#L81C1-L84C67) in ``pdr``.

The docstring for [the ``to_dict`` method](https://pdssbn.astro.umd.edu/tools/pds4_tools_docs/current/pds4_tools.reader.label_objects.html#pds4_tools.reader.label_objects.Label.to_dict) is here. It also includes e.g. a ``cast_values`` argument.

**Comment by Fenreg** [comment]
Dear all,

Regarding the issue at hand, the discrepancy between the set value for the skip_attributes option in the code and the reported default option documentation, I am of the opinion that the code value should match the reported documentation first and foremost.

Considering the larger question, i.e. how to deal with attributes, I am of a more radical opinion and although several PDS4 dictionaries do not include labels requiring attributes, I would, as a user, prefer to be confronted to a single datatype rather alternating system.
Therefore, I would favor a solution in which the user would have an datatype listing value, unit for each and any label.

**Comment by LevN0** [comment]
@Fenreg 

To clarify, you would prefer,

```xml
<Table_Character>
    <offset unit="byte">0</offset>
    <records>76</records>
    ...
</Table_Character>
```

Translate to,

```python
{
    "Table_Character": {
        "offset": {
            "@unit": "byte",
            "_text": "0"
        },
        "records": {
            "_text": "76"
        }
    }
}
```

Did I understand correctly?

**Comment by m-stclair** [comment]
I understand @fenreg as meaning that this snippet should translate to:

```
    "Table_Character": {
        "offset": {
            "@unit": "byte",
            "_text": "0"
        },
        "records": {
           "@unit": None,
            "_text": "76"
        }
``` 
in order to create complete consistency between expected keys of mappings associated with all PDS4 attributes.
For _complete_ consistency, however, a solution this should include _all_ legal XML attributes associated with any PDS4 attribute -- for instance, both "offset" and "records" above -- and maybe even "Table_Character" -- should also have `"nil": None`  and `"nilReason": None` items, in addition to many others. 

I am concerned that a solution like this will make parsed labels difficult to read and require additional filtering code for users who wish to translate these Python objects back into XML.

**Comment by Fenreg** [comment]
I do apologize, @LevN0, for not answering sooner and I do thank you @m-stclair for highlighting the logic of my previous answer.

This question that you raise, @m-stclair, is actually the one I am dealing with presently, as I have to create ancillary data to science observations and need to copy general information relative to these observations back into the main PDS4 dictionaries of their lblx files.
I have implemented the corrective to ensure the lecture of all attributes as discussed above, and in the end, either way works in my view, i.e. setting an exception for a specific label, or - as I did prior to finding out about skip_attributes - having a "to_dict" method to include a "unit" key for each and every label.

All the best,

**Comment by LevN0** [comment]
The one thing I definitely will not do is add attributes not in the label into the result. This would require having the any dictionary at hand, which the code does not and will not. The most data that can be included by PDS4 Tools here is what is present in the label itself.

Thus the options for when ``skip_attributes=False`` for,

```xml
<Table_Character>
    <offset unit="byte">0</offset>
    <records>76</records>
    ...
</Table_Character>
```

are either,

```python
{
    "Table_Character": {
        "offset": {
            "@unit": "byte",
            "_text": "0"
        },
        "records": {
            "_text": "76"
        }
    }
}
```

or

```python
{
    "Table_Character": {
        "offset": {
            "@unit": "byte",
            "_text": "0"
        },
       "records": "76"
    }
}
```

**Comment by m-stclair** [comment]
On consideration, my vote is:

1. Make `skip_attributes=True` by default. For most applications, the XML attributes in PDS4 labels are not important.
2. When `skip_attributes=False`, always make the values of keys corresponding to PDS4 attributes `dicts`, whether or not they have XML attributes. This is basically because type consistency is convenient.

There are basically no options here that are not annoying compromises: XML tags simply do not cleanly translate to idiomatic Python `Mappings`. If a user needs perfectly reliable access to all XML affordances, they should use the `Label` object itself , or supplement `pds4-tools` with a high-level XML manipulation toolchain like `bs4` + `lxml`.

**Comment by m-stclair** [comment]
I take it back: I vote *don't* make every value corresponding to a PDS4 attribute a `dict`. This might have been a good data design decision at some point, but it will be a catastrophically breaking change for many pieces of downstream software, which is a high cost for a tweaky little marginal improvement.
