### ISSUE TITLE
table read failure with numpy >= 2.0.0

### ISSUE THREAD

**Issue by m-stclair** [Small-Bodies-Node/pds4_tools#93]
Numpy 2.0.0 removes `np.unicode_`. Because `pds4_tools.reader.data_types.pds_to_numpy()` checks the type of character data against `np.unicode_`, `pds4_tools` will throw an exception when reading any table with character data. The officially-recommended fix is to replace `np.unicode_` with `np.string_` (I think `np.unicode_` had just been an alias for `np.string_` for a while).

**Comment by LevN0** [comment]
Thank you for reporting. Will take a look at this, and what else NumPy 2.0 breaks.

**Comment by LevN0** [comment]
The lack of a release comes entirely from my lack of time to work on this.

I think I've made the decision to split releases of the `pds4_tools` package and PDS4 Viewer distributable, as building the latter from the former currently requires a lot of unfortunate manual work due to lack of time to automate it and complexity across the many versions of OS' it supports. 

I will try to make a release this weekend. That said, let's keep release discussion to #69.
